# Generated by Django 2.1.14 on 2019-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('a_materno', models.CharField(max_length=50)),
                ('a_paterno', models.CharField(max_length=50)),
                ('sexo', models.BooleanField()),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_registro', models.DateTimeField(verbose_name='Fecha de registro en el servidor')),
            ],
        ),
    ]
