# Generated by Django 2.1.14 on 2019-11-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Empleado',
        ),
    ]
